
set(NIGHTFEARSX_SRC
        ./source/Camera2D.cpp
        ./source/ResourceManager.h
        ./source/Gizmos.cpp
        ./source/Camera.cpp
        ./source/Particle.cpp
        ./source/reference.h
        ./source/Application.cpp
        ./source/Application.h
        ./source/Sprite.cpp
        ./source/Component.cpp
        ./source/GameScene.cpp
        ./source/NavMesh.h
        ./source/inputSystem.cpp
        ./source/global_val.h
        ./source/Color.cpp
        ./source/font.h
        ./source/Gizmos.h
        ./source/Atlas.h
        ./source/scene.h
        ./source/resource.h
        ./source/Texture.h
        ./source/paths.cpp
        ./source/inputSystem.h
        ./source/LevelEntity.cpp
        ./source/GameObject.h
        ./source/scene.cpp
        ./source/pch.cpp
        ./source/framework.h
        ./source/Spotlight.h
        ./source/ObjectParser.cpp
        ./source/Renderer.h
        ./source/SpriteRenderer.cpp
        ./source/NavMesh.cpp
        ./source/Vec2.cpp
        ./source/ObjectParser.h
        ./source/time.h
        ./source/Color.h
        ./source/Spotlight.cpp
        ./source/Transform.h
        ./source/Atlas.cpp
        ./source/Player.h
        ./source/Vec2.h
        ./source/Behaviour.h
        ./source/Transform.cpp
        ./source/Mathf.h
        ./source/timeline.cpp
        ./source/Texture.cpp
        ./source/sysInfo.h
        ./source/Terrain2D.cpp
        ./source/time.cpp
        ./source/Object.cpp
        ./source/Light.cpp
        ./source/MainMenu.cpp
        ./source/timeline.h
        ./source/ui.h
        ./source/Terrain2D.h
        ./source/Particle.h
        ./source/ui.cpp
        ./source/controls.cpp
        ./source/Camera.h
        ./source/Object.h
        ./source/types.h
        ./source/sysInfo.cpp
        ./source/Light.h
        ./source/SpriteRenderer.h
        ./source/Camera2D.h
        ./source/GameObject.cpp
        ./source/framework_ex.h
        ./source/MainMenu.h
        ./source/controls.h
        ./source/CMakeLists.txt
        ./source/GameScene.h
        ./source/ResourceManager.cpp
        ./source/Sprite.h
        ./source/Player.cpp
        ./source/paths.h
        ./source/Renderer.cpp
        ./source/types.cpp
        ./source/CMakeLists.txt.user
        ./source/Mathf.cpp
        ./source/LevelEntity.h
        ./source/Component.h
        ./source/pch.h
        ./source/font.cpp
        ./source/main.cpp PARENT_SCOPE
    )
